// Builds src/data/flags.ts: 3:2 SVG flags for every quiz country
// (country-flag-icons, MIT), inlined so the game makes no requests.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const src = fs.readFileSync(path.join(ROOT, 'src', 'game', 'countries.ts'), 'utf8');
const codes = [...src.matchAll(/\[\d(?:\.\d)?, '([A-Z ]+)'\]/g)].flatMap((m) => m[1].split(' ')).sort();
const dir = path.join(ROOT, 'node_modules', 'country-flag-icons', '3x2');
const flags = {};
for (const c of codes) {
  const svg = fs
    .readFileSync(path.join(dir, `${c}.svg`), 'utf8')
    .replace(/<\?xml[^>]*>/, '')
    .replace(/\s+/g, ' ')
    .replace(/> </g, '><')
    .trim();
  flags[c] = svg;
}
const out =
  '// Generated by tools/geo/flags.mjs from country-flag-icons (MIT). Do not edit.\n' +
  `export const FLAGS: Record<string, string> = ${JSON.stringify(flags)};\n`;
fs.writeFileSync(path.join(ROOT, 'src', 'data', 'flags.ts'), out);
console.log('flags', codes.length, (out.length / 1024).toFixed(0) + ' KB');
