// Builds src/data/tz.ts: IANA time zone -> ISO country, used to guess the
// player's home country offline (no geo-IP request is allowed on Poki).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import ct from 'countries-and-timezones';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const all = ct.getAllTimezones({ deprecated: true });

const byRegion = {};
for (const [name, z] of Object.entries(all).sort()) {
  const country = z.countries?.[0] || (z.aliasOf && all[z.aliasOf]?.countries?.[0]);
  if (!country || !name.includes('/') || name.startsWith('Etc/')) continue;
  const cut = name.indexOf('/');
  const region = name.slice(0, cut);
  (byRegion[region] ||= []).push(name.slice(cut + 1) + '=' + country);
}
// "Region|City=CC,City=CC;Region|..." keeps the table small.
const packed = Object.entries(byRegion)
  .map(([r, list]) => r + '|' + list.join(','))
  .join(';');
const out =
  '// Generated by tools/geo/tz.mjs from countries-and-timezones. Do not edit.\n' +
  `export const TZ_TABLE = '${packed}';\n`;
fs.writeFileSync(path.join(ROOT, 'src', 'data', 'tz.ts'), out);
console.log('tz zones', Object.values(byRegion).reduce((s, l) => s + l.length, 0), 'bytes', out.length);
